### ISSUE TITLE
Update Date Time label in Online Events section

### ISSUE THREAD

**Issue by KeenWarrior** [codeforcauseorg/codeforcause.org#13]
Expected result : 

<img width="890" alt="Screenshot 2020-06-26 at 6 33 18 PM" src="https://user-images.githubusercontent.com/25343183/85860423-6990b200-b7dc-11ea-8303-e4238c2a5eab.png">

**Comment by Abhishek-kumar09** [comment]
@KeenWarrior @GangaChatrvedi, what is the good approach to add dates in events, so that it could gain functionalities like showing today, tomorrow, etc.
I was looking here for adding date https://www.w3schools.com/js/js_dates.asp. Is it the good way to add date or we have something else that comes out of the box for **react**

**Comment by GangaChatrvedi** [comment]
You don't really need to look for alternative in react for this. You can do it using plain JS.

**Comment by Abhishek-kumar09** [comment]
@GangaChatrvedi, I just realised that it is hardcoded time for now. We can fix it in the future. and javascript `Date()` object could help us in that. :)
