### ISSUE TITLE
[Feature request] better scrollbar.

### ISSUE THREAD

**Issue by harshhhdev** [codeforcauseorg/codeforcause.org#145]
![image](https://user-images.githubusercontent.com/69592270/97243011-b3f65f80-17cb-11eb-9846-ab05695dcb8f.png)

The current scroll bar, in my humble opinion, does not look very pretty (even worse than the default one). Now, compare this to something like, 

![image](https://user-images.githubusercontent.com/69592270/97243044-cc667a00-17cb-11eb-888d-d4161bb7855e.png)

and you can already start to see a massive difference.

**Comment by Abhishek-kumar09** [comment]
Oh yes, this scrollbar has been changed with this https://github.com/codeforcauseorg/codeforcause.org/pull/140. Its simple on mobile because mobiles have touches and don't need scrollbar most often, so *auto hiding*  the scrollbar on mobile, and a black scrollbar is made on the laptops and for larger screens, without that border ofcourse. 
Whats your opinion on it?

**Comment by harshhhdev** [comment]
Sounds good. Can I work on it?

**Comment by Abhishek-kumar09** [comment]
Its already in progress (That black border was somewhat looking bad, so removed that), this is deployed website: https://deploy-preview-140--eloquent-turing-542749.netlify.app/
You can check it out, and tell us if you need some further improvements in the scrollbars.

**Comment by harshhhdev** [comment]
Oh no, looks great now. Nice work :+1:
