### ISSUE TITLE
Add event date and time to calendar.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#41]
I think most of the developers use google calendar to manage events around them  to get reminded of the stuffs around them. Infact it is natively supported in android devices that could pop up the event dates and times in the notification panel. 

We can add a google calendar in our website that could just take us to google calendar to mark the event dates so that no one could miss or forget our live sessions.

Backend help: https://stackoverflow.com/a/21653600/13635762
Frontend: I think we can make a new button for this **or** click on the date(The green strip in which event date is written inside event section) that will take us to create an event.

**Comment by Trimankaur** [comment]
Hi , I would like to work on this issue. I have done some research , currently the 'Our Online Events' section shows the information about the past session. I was wondering where are you planning to add the google calendar part. 
![image](https://user-images.githubusercontent.com/29235241/89584677-12a9de00-d85a-11ea-8ebb-6840ea9bcd83.png)

**Comment by Abhishek-kumar09** [comment]
@KeenWarrior @GangaChatrvedi ping!

**Comment by KeenWarrior** [comment]
@Trimankaur We are planning to integrate youtube API to fetch our new streams. So that problem should be solved after that. 

Adding to google calendar is a separate challenge as we will need to create a google calendar event and associate its value to our event page.

I will check with team about the possibility of completing the base requirement for the same.

**Comment by Trimankaur** [comment]
Okay @KeenWarrior. Thank you for the clarification , let me know whenever the base requirements are fulfilled.
